configuration:
  template_dir:
  - "mobans/templates"
  - ".moban.d"
  configuration: echarts-themes-js.yml
targets:
  - README.md: custom_readme.md.jj2
  - output: CHANGELOG.md
    configuration: changelog.yml
    template: changelog.md.jj2
 
